# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "nerjs"
    labels:
      - "dependencies"
      - "bot"
    target-branch: "dependencies"
    open-pull-requests-limit: 5
    groups:
      # dev:
      #   patterns:
      #     - tempfile
      logging:
        patterns:
          - tracing-subscriber
          - tracing
      infrastructure:
        patterns:
          - tokio
          - anyhow
      serde:
        patterns:
          - serde
          - serde_json