[package]
name = "gitvol"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
axum = "0.8.4"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
sha2 = "0.10.9"
tokio = { version = "1.46.1", features = ["fs", "full", "macros", "process", "sync", "time", "tokio-macros"] }
tracing = { version = "0.1.41", features = ["std", "tracing-attributes", "async-await", "log", "release_max_level_debug", "max_level_trace"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
url = "2.5.4"

[dev-dependencies]
tempfile = "3.20.0"
