name: "CI (dependencies): tests, linter and build"

on:
  workflow_dispatch:
  push:
    branches:
      - dependencies 
  pull_request:
    branches:
      - dependencies 

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-CI]')"

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-check-


      - name: Check Rust formatting
        run: cargo fmt --all --check

  cargo-check:
    runs-on: ubuntu-latest
    needs: check-fmt

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-check-


      - name: Check Rust errors
        run: cargo check --all-targets --all-features

  build-and-tests:
    runs-on: ubuntu-latest
    needs: cargo-check

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-debug-


      - name: tests
        run: cargo test

      - name: debug build
        run: cargo build