name: "CI: tests, linter and build"

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip-CI]')"

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable rust tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-check-


      - name: Check Rust formatting
        run: cargo fmt --all --check

  cargo-check:
    runs-on: ubuntu-latest
    needs: check-fmt

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable rust tools
        uses: dtolnay/rust-toolchain@stable
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-check-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-check-


      - name: Check Rust errors
        # run: RUSTFLAGS="-D warnings" cargo check --all-targets --all-features
        run: cargo check --all-targets --all-features

  build-and-tests:
    runs-on: ubuntu-latest
    needs: cargo-check

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable rust tools
        uses: dtolnay/rust-toolchain@stable
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-debug-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-debug-


      - name: tests
        run: cargo test

      - name: debug build
        run: cargo build

  build-release:
    runs-on: ubuntu-latest
    needs: cargo-check

    steps:
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install stable rust tools
        uses: dtolnay/rust-toolchain@stable
            
      - name: Cache Cargo target directory
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-release-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-release-


      - name: build release
        run: cargo build --release