name: Formatting


on:
  workflow_dispatch:


jobs:
  fmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref_name }}

      - name: Install stable rust tools
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all

      - name: Check for changes
        id: git-diff
        run: |
          git diff --quiet || echo "changed=true" >> $GITHUB_OUTPUT


      - name: Commit and push changes
        if: steps.git-diff.outputs.changed == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "fix: apply rustfmt"
          git push origin ${{ github.ref_name }}
