name: "SYNC: dependencies with master"


on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PUBLISH_TOKEN }}
          ref: dependencies

      - name: fetch
        run: git fetch

      - name: merge master
        run: git merge origin/master -m "Sync master to dependencies [skip-CI]"

      - name: push into dependencies
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin dependencies